model_list:
  - model_name: gpt-5-1-openai
    litellm_params:
      model: openai/gpt-5.1
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-5-mini-openai
    litellm_params:
      model: openai/gpt-5-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-5-nano-openai
    litellm_params:
      model: openai/gpt-5-nano
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-4o-mini-openai
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: gpt-openai
    litellm_params:
      model: openai/gpt-4o-mini
      api_key: os.environ/OPENAI_API_KEY

  - model_name: claude-sonnet-4-6-anthropic
    litellm_params:
      model: anthropic/claude-sonnet-4-6
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: claude-haiku-4-5-anthropic
    litellm_params:
      model: anthropic/claude-haiku-4-5
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: gemini-3-flash-preview-api
    litellm_params:
      model: vertex_ai/gemini-3-flash-preview

  - model_name: gemini-2-5-flash-api
    litellm_params:
      model: vertex_ai/gemini-2.5-flash

  - model_name: gemini-2-5-flash-lite-api
    litellm_params:
      model: vertex_ai/gemini-2.5-flash-lite

  - model_name: qwen3.5-aggressive
    litellm_params:
      model: openai/qwen
      api_base: http://host.docker.internal:8080/v1
      api_key: sk-no-key-required
      rpm_limit: 1000

  - model_name: qwen3.5-heretic
    litellm_params:
      model: openai/qwen
      api_base: http://host.docker.internal:8080/v1
      api_key: sk-no-key-required
      rpm_limit: 1000

litellm_settings:
  drop_params: true

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
